# Generated by Django 3.2.15 on 2022-10-02 17:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('car_name', models.CharField(max_length=100)),
                ('car_drive_type', models.CharField(max_length=30)),
                ('num_of_seats', models.IntegerField()),
                ('num_of_luggages', models.IntegerField()),
                ('num_of_doors', models.IntegerField()),
                ('cost_par_day', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=200)),
                ('return_location', models.CharField(max_length=200)),
                ('Pick_up_date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('return_date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('full_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbooking.car')),
            ],
        ),
    ]
