# Generated by Django 3.2.15 on 2022-10-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='return_date_time',
            field=models.DateTimeField(),
        ),
    ]
