# Generated by Django 3.2.15 on 2022-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0002_alter_booking_return_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
