# Generated by Django 3.2.15 on 2022-10-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0007_rename_user_contact_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('cancled', 'cancled'), ('In Progress', 'In Progress')], default='In Progress', max_length=100),
        ),
    ]
