# Generated by Django 3.2.15 on 2022-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0008_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
